version: '3.8'

services:
  backend:
    build:
      context: ../app/backend  # Path to backend from docker folder
      dockerfile: Dockerfile  # Use the shared Dockerfile
    container_name: nestjs-backend
    volumes:
      - ../app/backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD:
      DATABASE_NAME: ecom
    networks:
      - ecom-net

  frontend:
    build:
      context: ../app/frontend  # Path to frontend from docker folder
      dockerfile: Dockerfile  # Use the shared Dockerfile
    container_name: react-frontend
    volumes:
    - ../app/frontend:/app
    ports:
      - "3001:3000"
    depends_on:
      - backend
    networks:
      - ecom-net

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: ecom
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ecom-net

networks:
  ecom-net:

volumes:
  mysql-data:
